name: MetalChat
main: com.norcode.bukkit.metalchat.MetalChat
version: 0.0.1-SNAPSHOT
author: metalhedd
depend: [Vault]

commands:
  tell:
    aliases: [msg, pm, whisper]
    description: sends a private message
    usage: /<command> <player> <message>
    permission: metalchat.pm
  reply:
    aliases: [r, "@"]
    description: replies to the last PM you recieved, or the last person you sent a PM to.
    permission: metalchat.pm
    usage: /<command> <message>
  afk:
    aliases: [away]
    descriptions: toggles away status
    permission: metalchat.afk
    usage: /<command> [<reason>]
  chatprefs:
    aliases: [preferences, prefs]
    description: adjust some per-player preferences
    permission: metalchat.prefs
    usage: |
      /<command> list - list preferences
      /<command> get <pref> - get a preference
      /<command> set <pref> [<value>] - set a preference.

permissions:
  metalchat.admin:
    default: op
    children:
      metalchat.afk: true
      metalchat.afk.noauto: true
      metalchat.afk.nokick: true
      metalchat.colors: true
      metalchat.prefs: true

  metalchat.prefs:
    default: true
  metalchat.afk:
    default: true
  metalchat.afk.noauto:
    default: op
  metalchat.afk.nokick:
    default: op
  metalchat.pm:
    default: true
  metalchat.global.chat:
    default: true
  metalchat.colors:
    default: op
